classdef transmissionlossclass
    %   Class definition for the common output of a propagaation model
    %   detailing the transmissison loss in a profile generated by a
    %   defined frequency.
    properties
        frequency;
        tlvector;
        profrange;
        profdepth;
        etime;
    end
    methods
        function obj=transmissionlossclass(frequency,tlvector,profrange,profdepth,etime)
            if nargin>0
                obj.frequency=frequency;
                obj.tlvector=tlvector;
                obj.profrange=profrange;
                obj.profdepth=profdepth;
                obj.etime=etime;
            end
        end
    end
end